steps:
  # Build Docker image with build argument
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_BASE_URL=https://kidemia-service-1007453817746.europe-west1.run.app'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kidemiafrontend/kidemia:$SHORT_SHA'
      - '.'
    id: 'build'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kidemiafrontend/kidemia:$SHORT_SHA'
    id: 'push'
    waitFor: ['build']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kidemia-frontend'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kidemiafrontend/kidemia:$SHORT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--port=8080'
      - '--min-instances=0'
      - '--max-instances=10'
    id: 'deploy'
    waitFor: ['push']

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kidemiafrontend/kidemia:$SHORT_SHA'

timeout: 1200s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY