steps:
  # Install dependencies
  - name: 'node:22-slim'
    entrypoint: npm
    args: ['ci', '--prefer-offline', '--no-audit']
    id: 'install'

  # Build the Vite app
  - name: 'node:22-slim'
    entrypoint: npm
    args: ['run', 'build']
    id: 'build'
    waitFor: ['install']
    env:
      - 'NODE_ENV=production'
      - 'VITE_BASE_URL=https://kidemia-service-1007453817746.europe-west1.run.app'
      # Add any other VITE_ environment variables here

  # Build container using Buildpacks (NO DOCKERFILE!)
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - build
      - 'gcr.io/$PROJECT_ID/kidemia-frontend:$SHORT_SHA'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=.'
      - '--env=GOOGLE_RUNTIME=nodejs'
      - '--env=GOOGLE_RUNTIME_VERSION=22'
    id: 'buildpack'
    waitFor: ['build']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kidemia-frontend'
      - '--image=gcr.io/$PROJECT_ID/kidemia-frontend:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--port=3000'
      - '--timeout=60'
      - '--set-env-vars=VITE_BASE_URL=https://kidemia-service-1007453817746.europe-west1.run.app'
    id: 'deploy'
    waitFor: ['buildpack']

images:
  - 'gcr.io/$PROJECT_ID/kidemia-frontend:$SHORT_SHA'

# Build timeout
timeout: 2400s

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'

