export const QueryKeys = {
  user: "user",
  allSubjects: "subjects",
  allTopics: "topics",
  allQuestions: "questions",
  allAssessment: "allAssessment",
  assessmentQuestions: "assessmentQuestions",
  assesstmentAttempt: "assesstmentAttempt",
  assessmentCategories: "assessmentCategories",
  assessmentConfig: "assessmentConfig",
  testDetails: "testDetails",
  testAttempt: "testAttempt",
  categories: "categories",
  leaderboard: "leaderboard",
  analytics: "analytics",
  pricing: "pricing",
  wallet: "wallet",
  mysubscription: "mysubscription",

  guardianProfile: "guardianProfile",
  categoryChangeRequests: "categoryChangeRequests",
  comprehensiveReport: "comprehensiveReport",
  wardReport: "wardReport",
  wardStats: "wardStats",
  myWards: "myWards",
  subscriptionMembers: "subscriptionMembers",
  assignments: "assignments",
  wardAssignments: "wardAssignments",
  assignmentDetail: "assignmentDetail",
} as const;
