export const QueryKeys = {
  user: "user",
  allSubjects: "subjects",
  allTopics: "topics",
  allQuestions: "questions",
  allAssessment: "allAssessment",
  assessmentQuestions: "assessmentQuestions",
  assesstmentAttempt: "assesstmentAttempt",
  testDetails: "testDetails",
  testAttempt: "testAttempt",
  categories: "categories",
  leaderboard: "leaderboard",
  analytics: "analytics",
  pricing: "pricing",
  wallet: "wallet",
} as const;
